# Generated by Django 4.0.3 on 2022-05-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employe',
        ),
    ]
