# Generated by Django 4.0.3 on 2022-05-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
